// src/app/layouts/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { JwtService } from '../../services/jwt-service';
import { Router } from '@angular/router';
import { MenuService } from '../../services/menu-service';
import { SidebarItem } from '../../models/sidebar-item.model';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  showMobileMenu = false;
  expandedItems: Set<string> = new Set();

  sidebarItems: SidebarItem[] = [];

  selectedUrl: string = '';

  userEmail: string | null = null;
  userRole: string | null = null;

  constructor(private jwtService: JwtService, private router: Router, private menuService: MenuService) {
    this.userEmail = this.jwtService.getEmail();
    this.userRole = this.jwtService.getRole();
    this.sidebarItems = this.menuService.getMenuItems();
    this.selectedUrl = this.router.url;
    
    // Expandir automáticamente el item padre si la URL actual pertenece a una subsección
    this.checkAndExpandParent();
  }

  /**
   * Obtiene el nombre descriptivo del rol del usuario
   */
  get userRoleDisplay(): string {
    if (!this.userRole) return '';

    switch (this.userRole.toLowerCase()) {
      case 'efector':
        return 'Efector de salud';
      case 'agente':
        return 'Agente comunitario';
      case 'usmya':
        return 'USMYA';
      case 'referente':
        return 'Referente afectivo';
      case 'admin':
        return 'Administrador';
      default:
        return this.userRole; // Retorna el rol original si no coincide con ninguno
    }
  }

  private checkAndExpandParent(): void {
    for (const item of this.sidebarItems) {
      if (item.subsections) {
        const hasActiveSubsection = item.subsections.some(sub => this.isActive(sub.url));
        if (hasActiveSubsection) {
          this.expandedItems.add(item.label);
          break;
        }
      }
    }
  }

  logout() {
    this.jwtService.removeToken();
    this.router.navigate(['/login']);
    this.showMobileMenu = false;
    // Restaurar scroll del body
    document.body.style.overflow = '';
  }

  toggleMobileMenu() {
    this.showMobileMenu = !this.showMobileMenu;
    
    // Bloquear/desbloquear scroll del body
    if (this.showMobileMenu) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  }

  toggleSubsections(item: SidebarItem, event: Event): void {
    event.stopPropagation();
    if (item.subsections) {
      if (this.expandedItems.has(item.label)) {
        this.expandedItems.delete(item.label);
      } else {
        this.expandedItems.add(item.label);
      }
    }
  }

  isExpanded(item: SidebarItem): boolean {
    return this.expandedItems.has(item.label);
  }

  isActive(url: string): boolean {
    return this.selectedUrl === url;
  }

  selectItem(url: string) {
    this.selectedUrl = url;
    this.router.navigate([url]);
    this.showMobileMenu = false;
    // Restaurar scroll del body
    document.body.style.overflow = '';
  }
}
<nav class="navbar">
  <div class="navbar__left">
    <img src="assets/logo.png" alt="Logo" class="navbar__logo" />
    <span class="navbar__app-name">MappA</span>
  </div>
  <div class="navbar__user-info">
    <span class="navbar__user-name">{{ userEmail }}</span>
    <span class="navbar__user-role">{{ userRoleDisplay }}</span>
  </div>
  <div class="navbar__right">
    <button class="navbar__logout" (click)="logout()" title="Cerrar sesión">
      <img src="assets/logout.svg" alt="Logout" />
    </button>
    <button class="navbar__hamburger" (click)="toggleMobileMenu()" title="Menú">
      <img src="assets/hamburger.svg" alt="Menu" />
    </button>
    
    <!-- Mobile Menu -->
    @if (showMobileMenu) {
      <div class="navbar__mobile-menu">
        <!-- <div class="mobile-menu__header">
          <div class="mobile-menu__user-info">
            <div class="mobile-menu__user-avatar">
              {{ userEmail ? userEmail.charAt(0).toUpperCase() : 'U' }}
            </div>
            <div class="mobile-menu__user-details">
              <span class="mobile-menu__user-name">{{ userEmail }}</span>
              <span class="mobile-menu__user-role">{{ userRoleDisplay }}</span>
            </div>
          </div>
        </div> -->

        <nav class="mobile-menu__nav">
          <ul>
            @for (item of sidebarItems; track item.label) {
              <li class="mobile-menu__item">
                <!-- Item sin subsecciones -->
                @if (!item.subsections) {
                  <a 
                    [routerLink]="item.url"
                    class="mobile-menu__link"
                    [class.selected]="isActive(item.url)"
                    (click)="selectItem(item.url)">
                    <span class="mobile-menu__icon">
                      <img [src]="item.icon" alt="icon" />
                    </span>
                    <span class="mobile-menu__label">{{ item.label }}</span>
                  </a>
                } @else {
                  <!-- Item con subsecciones -->
                  <div class="mobile-menu__parent-item">
                    <div 
                      class="mobile-menu__link mobile-menu__link--parent"
                      [class.expanded]="isExpanded(item)"
                      (click)="toggleSubsections(item, $event)">
                      <span class="mobile-menu__icon">
                        <img [src]="item.icon" alt="icon" />
                      </span>
                      <span class="mobile-menu__label">{{ item.label }}</span>
                      <span class="mobile-menu__arrow" [class.rotated]="isExpanded(item)">
                        ›
                      </span>
                    </div>
                    
                    <!-- Subsecciones -->
                    @if (isExpanded(item)) {
                      <ul class="mobile-menu__subsections">
                        @for (subsection of item.subsections; track subsection.label) {
                          <li class="mobile-menu__subsection">
                            <a 
                              [routerLink]="subsection.url"
                              class="mobile-menu__link mobile-menu__link--child"
                              [class.selected]="isActive(subsection.url)"
                              (click)="selectItem(subsection.url)">
                              <span class="mobile-menu__label">{{ subsection.label }}</span>
                            </a>
                          </li>
                        }
                      </ul>
                    }
                  </div>
                }
              </li>
            }
          </ul>
        </nav>

        <!-- Logout button -->
        <div class="mobile-menu__footer">
          <button class="mobile-menu__logout-btn" (click)="logout()">
            <span class="mobile-menu__logout-icon">
              <img src="assets/logout.svg" alt="Logout" />
            </span>
            <span class="mobile-menu__logout-label">Cerrar sesión</span>
          </button>
        </div>
      </div>
    }
  </div>
</nav>

// src/layouts/Navbar.jsx
import React, { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { menuService } from '../services';
import { useAuthStore } from '../store/authStore';
import logoImage from '../assets/logo.png';
import logoutIcon from '../assets/logout.svg';
import hamburgerIcon from '../assets/hamburger.svg';

const roleDisplay = {
  admin: 'Administrador',
  agente: 'Agente comunitario',
  efector: 'Efector de salud',
  referente: 'Referente afectivo',
  usmya: 'USMYA',
};

const isPathActive = (currentPath, targetPath) => {
  if (!targetPath) return false;
  if (currentPath === targetPath) return true;
  return currentPath.startsWith(`${targetPath}/`);
};

const hasActiveSubsection = (item, pathname) =>
  (item.subsections || []).some((subsection) => isPathActive(pathname, subsection.url));

function Navbar() {
  const navigate = useNavigate();
  const location = useLocation();

  const user = useAuthStore((state) => state.user);
  const role = useAuthStore((state) => state.getRole());
  const logout = useAuthStore((state) => state.logout);

  const items = useMemo(() => menuService.getMenuItems(role), [role]);
  const [showMobileMenu, setShowMobileMenu] = useState(false);
  const [expandedItems, setExpandedItems] = useState({});

  useEffect(() => {
    setExpandedItems((previous) => {
      const next = { ...previous };
      items.forEach((item) => {
        if (item.subsections?.length && hasActiveSubsection(item, location.pathname)) {
          next[item.label] = true;
        }
      });
      return next;
    });
  }, [items, location.pathname]);

  useEffect(() => {
    if (!showMobileMenu) return undefined;

    document.body.style.overflow = 'hidden';

    return () => {
      document.body.style.overflow = '';
    };
  }, [showMobileMenu]);

  useEffect(() => {
    setShowMobileMenu(false);
    document.body.style.overflow = '';
  }, [location.pathname]);

  const onLogout = () => {
    logout();
    navigate('/login');
  };

  const toggleSubsections = (itemLabel) => {
    setExpandedItems((previous) => ({
      ...previous,
      [itemLabel]: !previous[itemLabel],
    }));
  };

  const selectItem = (url) => {
    navigate(url);
    setShowMobileMenu(false);
  };

  return (
    <nav className="navbar">
      <div className="navbar__left">
        <img src={logoImage} alt="Logo" className="navbar__logo" />
        <span className="navbar__app-name">MappA</span>
      </div>

      <div className="navbar__user-info">
        <span className="navbar__user-name">{user?.email || 'usuario@demo.com'}</span>
        <span className="navbar__user-role">{roleDisplay[role] || role || 'Invitado'}</span>
      </div>

      <div className="navbar__right">
        <button className="navbar__logout" type="button" onClick={onLogout} title="Cerrar sesion">
          <img src={logoutIcon} alt="Logout" />
        </button>

        <button
          className="navbar__hamburger"
          type="button"
          onClick={() => setShowMobileMenu((value) => !value)}
          title="Menu"
        >
          <img src={hamburgerIcon} alt="Menu" />
        </button>

        {showMobileMenu ? (
          <div className="navbar__mobile-menu">
            <nav className="mobile-menu__nav">
              <ul>
                {items.map((item) => {
                  const expanded = Boolean(expandedItems[item.label]);
                  const selected = hasActiveSubsection(item, location.pathname);

                  return (
                    <li className="mobile-menu__item" key={item.label}>
                      {!item.subsections?.length ? (
                        <button
                          className={`mobile-menu__link${isPathActive(location.pathname, item.url) ? ' selected' : ''}`}
                          type="button"
                          onClick={() => selectItem(item.url)}
                        >
                          <span className="mobile-menu__icon">
                            <img src={item.icon} alt={item.label} />
                          </span>
                          <span className="mobile-menu__label">{item.label}</span>
                        </button>
                      ) : (
                        <div className="mobile-menu__parent-item">
                          <button
                            className={`mobile-menu__link mobile-menu__link--parent${selected ? ' selected' : ''}${
                              expanded ? ' expanded' : ''
                            }`}
                            type="button"
                            onClick={() => toggleSubsections(item.label)}
                          >
                            <span className="mobile-menu__icon">
                              <img src={item.icon} alt={item.label} />
                            </span>
                            <span className="mobile-menu__label">{item.label}</span>
                            <span className={`mobile-menu__arrow${expanded ? ' rotated' : ''}`}>{'>'}</span>
                          </button>

                          {expanded ? (
                            <ul className="mobile-menu__subsections">
                              {item.subsections.map((subsection) => (
                                <li className="mobile-menu__subsection" key={subsection.url}>
                                  <button
                                    className={`mobile-menu__link mobile-menu__link--child${
                                      isPathActive(location.pathname, subsection.url) ? ' selected' : ''
                                    }`}
                                    type="button"
                                    onClick={() => selectItem(subsection.url)}
                                  >
                                    <span className="mobile-menu__label">{subsection.label}</span>
                                  </button>
                                </li>
                              ))}
                            </ul>
                          ) : null}
                        </div>
                      )}
                    </li>
                  );
                })}
              </ul>
            </nav>

            <div className="mobile-menu__footer">
              <button className="mobile-menu__logout-btn" type="button" onClick={onLogout}>
                <span className="mobile-menu__logout-icon">
                  <img src={logoutIcon} alt="Logout" />
                </span>
                <span className="mobile-menu__logout-label">Cerrar sesion</span>
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </nav>
  );
}

export default Navbar;
