// src/app/layouts/sidebar/sidebar.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { SidebarItem } from '../../models/sidebar-item.model';
import { MenuService } from '../../services/menu-service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  @Input() items: SidebarItem[] = [];
  @Input() selectedUrl: string = '';

  sidebarItems: SidebarItem[] = [];
  expandedItems: Set<string> = new Set();

  constructor(
    private menuService: MenuService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.sidebarItems = this.menuService.getMenuItems();
    // Establecer la URL actual como seleccionada
    this.selectedUrl = this.router.url;

    // Expandir automáticamente el item padre si la URL actual pertenece a una subsección
    this.checkAndExpandParent();
  }

  private checkAndExpandParent(): void {
    for (const item of this.sidebarItems) {
      if (item.subsections) {
        const hasActiveSubsection = item.subsections.some(sub => this.isActive(sub.url));
        if (hasActiveSubsection) {
          this.expandedItems.add(item.label);
          break;
        }
      }
    }
  }

  get activeUrl(): string {
    return this.selectedUrl;
  }

  isActive(url: string): boolean {
    // Si la URL termina con *, considerar que coincide con cualquier ruta que empiece con esa URL sin el *
    if (url.endsWith('*')) {
      const baseUrl = url.slice(0, -1); // Remover el *
      return this.selectedUrl.startsWith(baseUrl);
    }
    return this.selectedUrl === url;
  }

  toggleSubsections(item: SidebarItem): void {
    if (item.subsections) {
      if (this.expandedItems.has(item.label)) {
        this.expandedItems.delete(item.label);
      } else {
        this.expandedItems.add(item.label);
      }
    }
  }

  isExpanded(item: SidebarItem): boolean {
    return this.expandedItems.has(item.label);
  }

  selectItem(url: string) {
    // Si la URL termina con *, navegar a la URL base (sin el *)
    const actualUrl = url.endsWith('*') ? url.slice(0, -1) + '-general' : url;
    this.selectedUrl = actualUrl;
    this.router.navigate([actualUrl]);
  }
}

<aside class="sidebar">
  <nav class="sidebar__nav">
    <ul>
      <ng-container *ngFor="let item of sidebarItems">
        <li class="sidebar__item">
          <!-- Item principal -->
          <div class="sidebar__main-item"
               [class.expanded]="isExpanded(item)"
               [class.has-subsections]="item.subsections">
            <a *ngIf="!item.subsections; else parentLink"
               [routerLink]="item.url"
               routerLinkActive="selected"
               class="sidebar__link"
               (click)="selectItem(item.url)">
              <span class="sidebar__icon">
                <img [src]="item.icon" alt="icon" />
              </span>
              <span class="sidebar__label">
                {{ item.label }}
              </span>
            </a>

            <ng-template #parentLink>
              <div class="sidebar__link sidebar__link--parent"
                   (click)="toggleSubsections(item)">
                <span class="sidebar__icon">
                  <img [src]="item.icon" alt="icon" />
                </span>
                <span class="sidebar__label">
                  {{ item.label }}
                </span>
                <span class="sidebar__arrow" [class.rotated]="isExpanded(item)">
                  ›
                </span>
              </div>
            </ng-template>
          </div>

          <!-- Subsecciones -->
          <ng-container *ngIf="item.subsections">
            <ul class="sidebar__subsections" [class.expanded]="isExpanded(item)">
              <li *ngFor="let subsection of item.subsections" class="sidebar__subsection">
                <a [routerLink]="subsection.url"
                   routerLinkActive="selected"
                   class="sidebar__link sidebar__link--child"
                   (click)="selectItem(subsection.url)">
                  <span class="sidebar__label">
                    {{ subsection.label }}
                  </span>
                </a>
              </li>
            </ul>
          </ng-container>
        </li>
      </ng-container>
    </ul>
  </nav>
</aside>

// src/layouts/Sidebar.jsx
import React, { useEffect, useMemo, useState } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { menuService } from '../services';
import { useAuthStore } from '../store/authStore';

const isPathActive = (currentPath, targetPath) => {
  if (!targetPath) return false;
  if (currentPath === targetPath) return true;
  return currentPath.startsWith(`${targetPath}/`);
};

const hasActiveSubsection = (item, pathname) =>
  (item.subsections || []).some((subsection) => isPathActive(pathname, subsection.url));

function Sidebar() {
  const role = useAuthStore((state) => state.getRole());
  const items = useMemo(() => menuService.getMenuItems(role), [role]);
  const location = useLocation();
  const [expandedItems, setExpandedItems] = useState({});

  useEffect(() => {
    setExpandedItems((previous) => {
      const next = { ...previous };
      items.forEach((item) => {
        if (item.subsections?.length && hasActiveSubsection(item, location.pathname)) {
          next[item.label] = true;
        }
      });
      return next;
    });
  }, [items, location.pathname]);

  const toggleSubsections = (itemLabel) => {
    setExpandedItems((previous) => ({
      ...previous,
      [itemLabel]: !previous[itemLabel],
    }));
  };

  return (
    <aside className="sidebar">
      <nav className="sidebar__nav">
        <ul>
          {items.map((item) => {
            const expanded = Boolean(expandedItems[item.label]);
            const parentSelected = hasActiveSubsection(item, location.pathname);

            return (
              <li className="sidebar__item" key={item.label}>
                {!item.subsections?.length ? (
                  <NavLink
                    to={item.url}
                    className={({ isActive }) => `sidebar__link${isActive ? ' selected' : ''}`}
                  >
                    <span className="sidebar__icon">
                      <img src={item.icon} alt={item.label} />
                    </span>
                    <span className="sidebar__label">{item.label}</span>
                  </NavLink>
                ) : (
                  <>
                    <div className="sidebar__main-item has-subsections">
                      <button
                        className={`sidebar__link sidebar__link--parent${parentSelected ? ' selected' : ''}`}
                        type="button"
                        onClick={() => toggleSubsections(item.label)}
                      >
                        <span className="sidebar__icon">
                          <img src={item.icon} alt={item.label} />
                        </span>
                        <span className="sidebar__label">{item.label}</span>
                        <span className={`sidebar__arrow${expanded ? ' rotated' : ''}`}>›</span>
                      </button>
                    </div>
                    <ul className={`sidebar__subsections${expanded ? ' expanded' : ''}`}>
                      {item.subsections.map((subsection) => (
                        <li className="sidebar__subsection" key={subsection.url}>
                          <NavLink
                            to={subsection.url}
                            className={({ isActive }) =>
                              `sidebar__link sidebar__link--child${isActive ? ' selected' : ''}`
                            }
                          >
                            <span className="sidebar__label">{subsection.label}</span>
                          </NavLink>
                        </li>
                      ))}
                    </ul>
                  </>
                )}
              </li>
            );
          })}
        </ul>
      </nav>
    </aside>
  );
}

export default Sidebar;
